apiVersion: v1
kind: Pod
metadata:
        name: testapp
spec:
        containers:
                - image: gcr.io/kuar-demo/kuard-amd64:1
                  name: kuard
                  livenessProbe:
                          httpGet:
                                  path: /healthy
                                  port: 8080
                          initialDelaySeconds: 5
                          timeoutSeconds: 1
                          periodSeconds: 10
                          failureTreshold: 3
                  resources:
                        requests:
                                cpu: "500m"
                                memory: "128Mi"
                        limits:
                                cpu: "1000m"
                                memory: "256Mi"        
                  ports:
                        - containerPort: 8080
                          name: http
                          protocol: TCP
                  volumeMounts:
                          - mountPath: "/data"
                            name: "testapp-data"
                  readinessProbe:
                          httpGet:
                                  path: /ready
                                  port: 8080
                          initialDelaySeconds: 30
                          timeoutSeconds: 1
                          periodSeconds: 10
                          failureTreshold: 3
                          
